### ISSUE TITLE
[question] Is it time to add org-vcard support to org-contact.el or start a new similar project?

### ISSUE THREAD

**Issue by tumashu** [flexibeast/org-vcard#20]

**Comment by flexibeast** [comment]
That's a question for the maintainers of `org-contact`, i think. :-) One thing to note, however: i'm not willing, at this point, to assign copyright of `org-vcard` to the FSF, which i'm guessing might in turn limit the willingness of the maintainers of `org-contact` to rely on `org-vcard`.

**Comment by tumashu** [comment]
org-contacts.el seemed stop development.....

**Comment by flexibeast** [comment]
It might well have .... but, yes, the status of `org-contacts` is something i can't address, i'm sorry! So i'm going to close this issue for now.

**Comment by Thaodan** [comment]
Org-Contacts is active again, it has some features that org-vcard doesn't have notably integration into other modes such as Gnus or Message-Mode.

**Comment by flexibeast** [comment]
Well, org-vcard was never designed as a *competitor* for org-contacts, but basically as a *supporting utility* for org-contacts: the intent of org-vcard was to facilitate turning vCard data into org-contacts data (specifically, what org-vcard calls the 'flat' style) and vice versa. It's basically an import/export tool for org-contacts.

All that said, it's been years since i've actively used Org and org-vcard for managing contacts, and i'm no longer interested in working on this package - i have many other things on my plate that are a much higher priority for me. So i'm going to seek a new maintainer.
