### ISSUE TITLE
Tag current version?

### ISSUE THREAD

**Issue by DamienCassou** [flexibeast/org-vcard#22]
Hi,

to facilitate packaging, it's better when projects have git tags. Could you please create a git tag on the latest commit?

Thanks

**Comment by DamienCassou** [comment]
That's also important when writing a package that depends on `org-vcard`. Currently, I have a warning in my code:

```
Use a non-snapshot version number for dependency on "org-vcard" if possible.
```

**Comment by flexibeast** [comment]
Firstly, sorry for the long delay in replying! i've had personal matters i've needed to attend to.

Good suggestion! i've just added a 'v0.1.0' tag, using semantic versioning. i've deliberately chosen '0.1.0' and not '1.0.0' because even though the `org-vcard` codebase has been fairly stable for several months now, i'm open to a significant refactoring as per [this](https://github.com/flexibeast/org-vcard/issues/23#issuecomment-164346837).

**Comment by DamienCassou** [comment]
Perfect, thanks!
